name: Pytest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Bağımlılıkları yükle
      run: pip install pytest

    - name: Testleri çalıştır
      run: pytest
